### ISSUE TITLE
Can't find class TableDataColumnAdapterDelegator in library

### ISSUE THREAD

**Issue by shyam-leanswift** [ISchwarz23/SortableTableView-ExampleApp#1]
https://github.com/ISchwarz23/SortableTableView-ExampleApp/blob/340b2e282c71f22c2f834e194fb0f5dd470d1079/app/src/main/java/com/sortabletableview/recyclerview/exampleapp/simpledata/SimpleDataExampleFragment.java#L53

I do not find this class as part of the standard open-source library that can be downloaded from Github. Is this only available in the paid version?

**Comment by ISchwarz23** [comment]
Yes, only the paid version contains the column adapter delegator which enables the creation of an adapter per column to reduce code duplication and to simplify the rearranging of columns.
Nevertheless you can use the TableDataAdapter of the free version, which has to contain the rendering of all the columns.

Best regards,
Ingo

**Comment by shyam-leanswift** [comment]
Ok. Thanks for the quick response. Awesome library by the way :)
